---
title: "Example 06 Bootstrapping"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ex06_Bootstrapping}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  options(rmarkdown.html_vignette.check_title = FALSE),
   fig.width=7, fig.height=8
)
```

```{r ex06_01}
library(FishStomachs)
suppressMessages(library(dplyr))
suppressMessages(library(readr))

load(file=file.path(system.file( package = "FishStomachs"),"extdata","ex03half.Rdata"),verbose=TRUE)


print(get_control(s),'bootstrapping')

############### add variables for bootstrapping
s<-edit_control(s, bootstrapping = list(
        boots_id = expression(paste(ship,rectangle,year,quarter,station,haul,sep='_')),
        boots_strata= expression(paste(year,quarter,pred_name))
        ))

print(get_control(s),'bootstrapping')

```

```{r ex06_02}

head(bootstrap_show(s,show=c("strata",'sample')[1]))

```


```{r ex06_03}

head(bootstrap_show(s,show=c("strata",'sample')[2]))

```


Creation of one set of data for bootstrapping
```{r ex06_04}

sb<-bootstrap_data(s)

```



Invariants for bootstrapping

```{r ex06_05}

# a very complex way of getting a list of prey names!
keep_prey <-(read_csv(file.path(system.file( package = "FishStomachs"),"extdata","species_info.csv"),
                      col_types = cols())  %>% 
               filter(prey_sp)  %>% select(species) %>% unique())$species
keep_prey #input is just a vector of prey names

s<-edit_control(s,sel_preys=keep_prey)

from_to <-make_from_to_species(inp_file=
        file.path(system.file( package = "FishStomachs"),"extdata","from_to_species.csv"))

s<-edit_control(s,
                calc_sub_strata=list(
                  # transform into relative weight before data are compiled
                  relative_weight=FALSE,      
                  # use number of stomach in the sample as weighting factor
                  weighting_factor=expression(n_tot),
                  # set file to NA when weighting_factor is given
                  weigthing_factor_file=NA
                ),
                calc_strata=list(
                  relative_weight=FALSE,
                  weighting_factor=expression(sqrt(mean_cpue)),
                  weigthing_factor_file=NA
                ),
                calc_total=list(
                  relative_weight=FALSE,
                  # set to NA when input is provided in a file
                  weighting_factor=NA,
                  # use data from a specified file (in those case, a file provided by the FishStomachs)
                  weigthing_factor_file=file.path(system.file( package = "FishStomachs"),"extdata","weighting_total.csv")
                )
)

```

  
Functions for processing observations to population diet. The code is copied from Example 03 and put into the function "do_boots".
```{r ex06_06}

do_boots<-function(s) {

# to keep information on bootstrap replicate  
rep_id<-unlist(s[['PRED']][1,'rep_id'])

# by sample
s<-redist_unidentified_prey_sp(s,dist_time=stratum_time,dist_area=sample_id,
        dist_pred_size=pred_size, do_only=c(1,2),from_to_species=from_to,
        by_prey_size=FALSE,remains_to_other = FALSE)

# by sub_area (=rectangel)
s<-redist_unidentified_prey_sp(s,dist_time=stratum_time,dist_area=stratum_sub_area,
        dist_pred_size=pred_size, do_only=c(1,2),from_to_species=from_to,
        by_prey_size=FALSE,remains_to_other = FALSE)

# by area (=roundfish area)
s<-redist_unidentified_prey_sp(s,dist_time=stratum_time,dist_area=stratum_area,
        dist_pred_size=pred_size, do_only=c(1,2,3),from_to_species=from_to,
        by_prey_size=FALSE,remains_to_other = FALSE)

# all areas
s<-redist_unidentified_prey_sp(s,dist_time=stratum_time,dist_area='All',
        dist_pred_size=pred_size, do_only=c(1,2,3),from_to_species=from_to,
        by_prey_size=FALSE,remains_to_other = FALSE)

# all areas and half-year (dist_time is changed)
s<-redist_unidentified_prey_sp(s,dist_time=paste(year,ifelse(quarter %in% c(1,2),'S1','S2')),
        dist_area='All',dist_pred_size=pred_size, do_only=c(1,2,3),from_to_species=from_to,
        by_prey_size=FALSE,remains_to_other = FALSE)

# the same as above, but unallocated remains to "other food".
s<-redist_unidentified_prey_sp(s,dist_time=paste(year,ifelse(quarter %in% c(1,2),'S1','S2')),
        dist_area='All',dist_pred_size=pred_size, do_only=c(1,2,3),from_to_species=from_to,
        by_prey_size=FALSE,remains_to_other = TRUE)

# by statum_area (=roundfish area)
s<-redist_unidentified_prey_lengths(s,dist_time=stratum_time,dist_area=stratum_area,
      dist_pred_size=pred_size,
      remains_to_other = FALSE, # do not add records with missing length allocation to "other food"
      others_to_other=TRUE      # do add other species that selected prey species to "other food"
      )

# within all areas
s<-redist_unidentified_prey_lengths(s,dist_time=stratum_time,dist_area='All',
      dist_pred_size=pred_size,remains_to_other = FALSE)

#  within all areas, and year (ignoring quarter)
s<-redist_unidentified_prey_lengths(s=s,dist_time=substr(stratum_time,1,4),dist_area='All',
      dist_pred_size=pred_size,remains_to_other = FALSE)

# as above, but with conversion of unallocated into "other"
s<-redist_unidentified_prey_lengths(s=s,dist_time=substr(stratum_time,1,4),dist_area='All',
      dist_pred_size=pred_size,remains_to_other = TRUE)

d<-calc_population_stom(s)
d[['PRED']]$rep_id<-rep_id
return(d)

}

```


  

```{r ex06_07}

n_boot<-1:3  # make 3 bootstrap replicates
b<-lapply(n_boot,function(x) bootstrap_data(s,seed=x,rep_id=x))

#convert observations into population diet
bt<-lapply(b,do_boots)

```




```{r ex06_08}

# Change predator and prey names into English names and weights into relative weights

bt2<-lapply(bt,function(x){
 x<-from_to_species_diet(x,pred_from_to=c("species","short"),prey_from_to=c("species","short"),
                               sp_info_file=file.path(system.file( package = "FishStomachs"),"extdata",'species_info.csv'))
 #Relative stomach contents
 x[['PREY']]<- x[['PREY']] %>% dplyr::group_by(key) %>% dplyr::mutate(prey_w=prey_w/sum(prey_w)*100) %>% dplyr::ungroup()
 return(x)

})

# comparison of two replicates
plotdif(d1=bt2[[1]],d2=bt2[[2]],show_plot=TRUE,cut_pred_size=c(1,4),cut_prey_size=c(2,4),addTitle=TRUE,
        tAngle=90, relative=FALSE,maxDif=3,
        byVar=c('year-quarter','year','quarter','none')[4])

```


```{r ex06_09}

# add zero prey weight for the combinations of prey species and prey sizes that may be missing from some replicates
bt3<-add_missing_boots(bt2)

plotdif(d1=bt3[[1]],d2=bt3[[2]],show_plot=TRUE,cut_pred_size=c(1,4),cut_prey_size=c(2,4),addTitle=TRUE,
        tAngle=90, relative=FALSE, maxDif=3,
        byVar=c('year-quarter','year','quarter','none')[4])

```


```{r ex06_10}

# sub set for plot
bt4<-lapply(bt3,function(x){
  subset(x,pred_name=='Cod' &  pred_size=='0400-0499' & stratum_time=='1991-Q1')
})


plotboots.size(b=bt4,show_plot=TRUE,cut_pred_size=c(1,10),cut_prey_size=c(2,4),addTitle=TRUE,tAngle=90)

```


```{r ex06_11}
# sub set for plot
bt4<-lapply(bt3,function(x){
  subset(x,pred_name=='Cod' & stratum_time=='1991-Q1' & !(pred_size %in% c('0100-0149','0150-0249')))
})


plotboots(b=bt4,show_plot=TRUE,cut_pred_size=c(2,4),addTitle=TRUE,tAngle=90)

```

